version: "3.9"
   
services:
  postgres_odoo:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoopass
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"
    expose:
      - "5433"  


  odoo:
    build:
      context: .
      dockerfile: compose_config/Dockerfile
    image: odoo_with_ext_server_web
    command: python /opt/odoo/odoo-10.0/odoo-bin -c /etc/odoo/odoo-server.conf
    volumes:
      - type: bind
        source: ./external_addons/
        target: /opt/odoo/external_addons
    ports:
      - "82:8069"
    depends_on:
      - postgres_odoo