version: "3.9"
   
services:
  postgres_odoo_14:
    image: postgres
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoopass
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"
    expose:
      - "5433"  


  odoo_14:
    build:
      context: .
      dockerfile: compose_config/Dockerfile
    image: odoo_with_ext_server_web
    command: python3 /opt/odoo/odoo-bin -c /etc/odoo/odoo-server.conf
    volumes:
      - type: bind
        source: ./external_addons/
        target: /opt/odoo/external_addons
    ports:
      - "80:8069"
    depends_on:
      - postgres_odoo_14